name: Manual translation regeneration

on:
  pull_request:
    types: [labeled]

jobs:
  regen:
    name: Re-run translations on label 'regen-needed'
    if: contains(github.event.pull_request.labels.*.name, 'regen-needed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Re-run translations
        run: tsx scripts/generate_translations.ts tasks.json

      - name: Commit regeneration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: regenerate translations after regen-needed label"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}